export const LAST_TIME_FETCHED = 'LAST_TIME_FETCHED';

export const TOKEN = 'TOKEN';

export const BASKET_ITEMS_LAYOUT = 'BASKET_ITEMS_LAYOUT';
export const TRAVELERS_BASKET_CHECKED = 'TRAVELERS_BASKET_CHECKED';
export const TRAVELERS = 'TRAVELERS';
export const DESTINATION = 'DESTINATION';
export const START_DATE = 'START_DATE';
export const END_DATE = 'END_DATE';

export const BASKET = 'BASKET';

export const PARTNER_SCANNED = 'PARTNER_SCANNED';

export const ACTIVITIES = 'ACTIVITIES';